# Generated by Django 4.2.11 on 2024-03-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
