# Generated by Django 4.2.11 on 2024-04-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_course_educationlevel_gender_jobtitle_language_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='key',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
