# Generated by Django 4.2.11 on 2024-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_alter_educationlevel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='key',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('technical', 'Técnico'), ('bachelor', 'Bacharelado'), ('teaching', 'Licenciatura'), ('technologist', 'Tecnólogo'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('post_doctorate', 'Pós-Doutorado'), ('other', 'Outros')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('technical', 'Técnico'), ('higher_education', 'Ensino Superior')], max_length=50),
        ),
    ]
