# Generated by Django 4.2.11 on 2024-04-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_alter_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtitle',
            name='key',
        ),
    ]
