# Generated by Django 4.2.11 on 2024-04-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0009_remove_jobtitle_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
