# Generated by Django 4.2.12 on 2024-05-06 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0010_alter_jobtitle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='area_of_interest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.areaofinterest'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.city'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.educationlevel'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.gender'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.state'),
        ),
    ]
