# Generated by Django 4.2.12 on 2024-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0011_alter_resume_area_of_interest_alter_resume_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('elementary', 'Fundamental'), ('high_school', 'Ensino Médio'), ('technical', 'Técnico'), ('bachelor', 'Bacharelado'), ('teaching', 'Licenciatura'), ('technologist', 'Tecnólogo'), ('master', 'Mestrado'), ('doctorate', 'Doutorado'), ('post_doctorate', 'Pós-Doutorado'), ('other', 'Outros')], default='other', max_length=50),
        ),
    ]
