# Generated by Django 4.2.12 on 2024-05-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.course'),
        ),
    ]
