# Generated by Django 4.2.11 on 2024-03-31 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
