from .resume import *
from .address import *
from .area_of_interest import *
from .education_level import *
from .education import *
from .gender import *
from .language_skill import *
from .professional_skill import *
from .work_experience import *
